export class Colegio
{
    codmodularColegio: String;
    anexoColegio: number;
    codLocalColegio: String;
    nombreColegio: String;
    nivelModalidadColegio: String;
    descrNivelModalidadColegio: String;
    desFormaColegio: String;
    tipSexoColegio: number;
    desTipSexoColegio: String;
    gestionColegio: number;
    desGestionColegio: String;
    gestionDepartamentalColegio: String;
    desGestionDepartamentalColegio: String;
    directorColegio: String;
    telefonoColegio: String;
    emailColegio: String;
    webColegio: String;
    direccionColegio: String;
    referenciaColegio: String;
    localidadColegio:String;
    codcpIneiColegio: String;
    codccppColegio: number;
    cenPobColegio: String;
    areaCensoColegio: number;
    dareaCensoColegio: String;
    codGeoColegio: String;
    departamentoColegio: String;
    provinciaColegio: String;
    distritoColegio: String;
    regionColegio: String;
    codooiiColegio: String;
    ugelColegio: String;
    latitudColegio: number;
    longitudColegio: number;
    tipprogramColegio: String;
    desTipprogramColegio: String;
    codTurnoColegio: number;
    desTurnoColegio: String;
    estadoColegio: number;
    desEstadoColegio: String;
    fecRegColegio: Date;
    fecActivacionColegio: Date;
    dniRepresentanteColegio: String;
    correoRepresentanteColegio: String;
}